### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_slim' [COLAB example demo]

### ISSUE THREAD

**Issue by raymondlo84** [ricardodeazambuja/colab_utils#3]
https://colab.research.google.com/github/ricardodeazambuja/colab_utils/blob/master/object_detection_tutorial_from_webcam.ipynb

The COLAB example failed to run at this step:

from object_detection.utils import ops as utils_ops

----

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-7035655b948a> in <module>()
----> 1 from object_detection.utils import ops as utils_ops
      2 from object_detection.utils import label_map_util
      3 from object_detection.utils import visualization_utils as vis_util

/usr/local/lib/python3.6/dist-packages/object_detection/utils/ops.py in <module>()
     26 from six.moves import zip
     27 import tensorflow.compat.v1 as tf
---> 28 import tf_slim as slim
     29 from object_detection.core import standard_fields as fields
     30 from object_detection.utils import shape_utils

ModuleNotFoundError: No module named 'tf_slim'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by ricardodeazambuja** [comment]
I found two bugs, both fixed now :)
